### ISSUE TITLE
备份电影一会就卡顿无法退出系统

### ISSUE THREAD

**Issue by nmxbb** [tabris17/doufen#2]
任务进程杀了之后再打开还是电影备份一会就卡住

**Comment by tabris17** [comment]
估计是服务进程挂了，看来要弄个文件日志才行

**Comment by tabris17** [comment]
另外问一下，卡住的现象具体怎样的？是有日志输出，但是停止不动了？

**Comment by nmxbb** [comment]
界面卡顿（所有按钮都失效，退出都不行），无显示日志输出。但是还是在备份的，文件夹大小有变化。只能从任务管理器杀进程重启。
