### ISSUE TITLE
设置及评论抓取问题

### ISSUE THREAD

**Issue by TheKiteRunning** [tabris17/doufen#7]
你好，感谢大作！以下是使用过程中遇到的几个问题：

- 首先，有一个地方挺奇怪，账户本身只有我一个，但如果不点击确认，就无法添加右边的任务。
- 广播评论不知道能否和广播任务合并。一开始想说评论没有抓取，原来是最后一个任务，大佬我错了～

烦请有空时回复，谢谢！

**Comment by tabris17** [comment]
1. 这个可以加个默认选中，只是偷懒，交互方面尽可能地少写代码。
2. 故意拆开的。因为广播评论备份（全部备份）是个很耗时的操作，不单单要抓取回复，还要抓取评论的用户数据，是个很容易导致账号被锁的操作，大家也尽量少用吧

**Comment by TheKiteRunning** [comment]
已经很赞了～我已经被锁了～广播和广播评论时不时都可以增量备份呢？

**Comment by tabris17** [comment]
由两个设置来控制
1.广播增量备份。只备份最新的广播。
2.广播回应活跃期。只备份活跃期时间段内的广播评论

**Comment by TheKiteRunning** [comment]
谢谢解答！
