### ISSUE TITLE
登陆成功，进入我的豆瓣又需要重新登录

### ISSUE THREAD

**Issue by TheKiteRunning** [tabris17/doufen#9]
之前已经备份了一部分。今天重新进来，想更新最忌你的广播之类，点击我的豆瓣，要求重新登录。重新登录后，点击我的豆瓣，仍然要求重新登录。

之前也有过类似情况，不同点在于那时候点击我的豆瓣会闪退，相同点绿色按钮对应的账户名处都只显示了我的域名，而能够备份时那里同时显示我的域名+当前用户名

**Comment by tabris17** [comment]
登录过豆瓣的网站吗？我怀疑你的帐号被豆瓣锁定了

**Comment by TheKiteRunning** [comment]
没有锁定啊，我电脑和手机都可以刷豆瓣的。现在更尴尬了，点击我的豆瓣：
![image](https://user-images.githubusercontent.com/24802332/41288453-ee48361c-6e78-11e8-9de5-19049cec722d.png)

**Comment by tabris17** [comment]
这……

难道sqlite3数据库损坏了……

头疼了……看来要做个备份数据的功能了

**Comment by TheKiteRunning** [comment]
已经不是第一次遇到了，还有额，如果更新的话，怎么样把之前备份的数据放到新版本的doufen里啊

**Comment by tabris17** [comment]
你用新的程序把原来的程序覆盖了就行，或者你把原来的程序下的var文件夹复制到新的程序文件夹下也行。

下载的数据都在那个var文件夹下。数据库的表结构都是向下兼容的，新版本可以打开老版本数据

**Comment by TheKiteRunning** [comment]
Hi, 我问题解决了。

首先把您说的var文件夹备份，然后删掉电脑里所有跟doufen相关的文件夹，重新下载一个安装包，替换掉var文件夹。重新打开的时候，同时显示了我的域名+当前用户名，果然我的豆瓣里面的内容都重新出现了。

**Comment by tabris17** [comment]
也是个怪问题，不过就算是解决了吧

**Comment by tabris17** [comment]
是BUG，待修复
